;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Boss.CounterTimeout",DevComment="")
+GameplayTagList=(Tag="Boss.GroggyEnd",DevComment="")
+GameplayTagList=(Tag="Boss.HitCounter",DevComment="")
+GameplayTagList=(Tag="Boss.PatternEnd",DevComment="")
+GameplayTagList=(Tag="Boss.StartAttack",DevComment="")
+GameplayTagList=(Tag="Boss.StartCounter",DevComment="")
+GameplayTagList=(Tag="Boss.StartPattern",DevComment="1")

